### ISSUE TITLE
Build Tegola Schema

### ISSUE THREAD

**Issue by syncush** [MapColonies/vector-layers-catalog#2]
We would like to show the following layers:
 - Bus stops
 - Gas Station
 - Highways
- Traffic lights
- Dirt roads

am I missing anything?

Tasks:
- Filter tags and values
- Build queries

**Comment by CptSchnitz** [comment]
We used the default one from osm-seed as it fit our requirements. see [imposm3.json](https://github.com/MapColonies/osm-seed/blob/develop/tiler-imposm/config/imposm3.json) and [config.toml](https://github.com/MapColonies/osm-seed/blob/develop/tiler-server/config/config.toml).
